{{- if .Values.fleet.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kibana.fullname" . }}-elastic-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kibana.fullname" . }}-elastic-agent
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kibana.fullname" . }}-elastic-agent
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kibana.fullname" . }}-elastic-agent
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kibana.fullname" . }}-elastic-agent
  apiGroup: rbac.authorization.k8s.io
{{- end }}
